AWSTemplateFormatVersion: 2010-09-09

Parameters:
  STAGE:
    Description: Stage name for the Cloudformation stack
    Type: String

Resources:
  AWSLambdaFullAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join ["_",[AWSLambdaFullAccessRole,!Ref STAGE]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSLambdaFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSESFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSSMFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchEventsFullAccess'
        - 'arn:aws:iam::542367334737:policy/CognitoRestrictedAccess'

Outputs:
  AWSLambdaFullAccessRoleARN:
    Value: !GetAtt AWSLambdaFullAccessRole.Arn
    Description: AWSLambdaFullAccessRole ARN
    Export:
      Name: !Sub '${AWS::StackName}-AWSLambdaFullAccessRoleARN'

  StackName:
    Value: !Ref 'AWS::StackName'