// Test data for afterMarketReportsData.functions.storeArrayOfOptions.test

module.exports.arrayOfOptions = [
    {
        "XJO":[
            {
                "type":"Call",
                "code":"XJO2Z8",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":5850,
                "stock":5953.4,
                "percentITM":"1.74",
                "last":0,
                "volume":160,
                "marginPrice":"4.73",
                "breakEvenPrice":"6323",
                "breakEvenPercent":"6.21"
            },
            {
                "type":"Call",
                "code":"XJO3M9",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":6000,
                "stock":5953.4,
                "percentITM":"-0.78",
                "last":0,
                "volume":10,
                "marginPrice":"3.88",
                "breakEvenPrice":"6388",
                "breakEvenPercent":"7.30"
            },
            {
                "type":"Call",
                "code":"XJOQA9",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":6400,
                "stock":5953.4,
                "percentITM":"-7.50",
                "last":1.78,
                "volume":109,
                "marginPrice":"2.05",
                "breakEvenPrice":"6605",
                "breakEvenPercent":"10.94"
            },
            {
                "type":"Put",
                "code":"XJOZM8",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":5400,
                "stock":5953.4,
                "percentITM":"-9.30",
                "last":2.26,
                "volume":20,
                "marginPrice":"1.81",
                "breakEvenPrice":"5219",
                "breakEvenPercent":"-12.34"
            },
            {
                "type":"Put",
                "code":"XJO3F8",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":5850,
                "stock":5953.4,
                "percentITM":"-1.74",
                "last":0,
                "volume":160,
                "marginPrice":"3.86",
                "breakEvenPrice":"5464",
                "breakEvenPercent":"-8.22"
            },
            {
                "type":"Put",
                "code":"XJO3E9",
                "expiry":"16/09/2021",
                "expiryInDays":379,
                "strike":4800,
                "stock":5953.4,
                "percentITM":"-19.37",
                "last":2.1,
                "volume":426,
                "marginPrice":"3.06",
                "breakEvenPrice":"4494",
                "breakEvenPercent":"-24.52"
            },
            {
                "type":"Put",
                "code":"XJOR57",
                "expiry":"16/09/2021",
                "expiryInDays":379,
                "strike":5400,
                "stock":5953.4,
                "percentITM":"-9.30",
                "last":0,
                "volume":426,
                "marginPrice":"4.64",
                "breakEvenPrice":"4936",
                "breakEvenPercent":"-17.09"
            }
        ]
    },
    {
        "AMC":[
            {
                "type":"Call",
                "code":"AMCNT8",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":14.75,
                "stock":14.85,
                "percentITM":"0.67",
                "last":0,
                "volume":200,
                "marginPrice":"0.99",
                "breakEvenPrice":"15.74",
                "breakEvenPercent":"5.99"
            },
            {
                "type":"Call",
                "code":"AMCQN7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":15,
                "stock":14.85,
                "percentITM":"-1.01",
                "last":0.68,
                "volume":35,
                "marginPrice":"0.85",
                "breakEvenPrice":"15.86",
                "breakEvenPercent":"6.77"
            }
        ]
    },
    {
        "ANZ":[
            {
                "type":"Call",
                "code":"ANZJO9",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":19,
                "stock":17.77,
                "percentITM":"-6.92",
                "last":0.7,
                "volume":200,
                "marginPrice":"0.90",
                "breakEvenPrice":"19.90",
                "breakEvenPercent":"11.99"
            },
            {
                "type":"Call",
                "code":"ANZC47",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":19.5,
                "stock":17.77,
                "percentITM":"-9.74",
                "last":0.53,
                "volume":50,
                "marginPrice":"0.71",
                "breakEvenPrice":"20.21",
                "breakEvenPercent":"13.73"
            },
            {
                "type":"Call",
                "code":"ANZTI7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":22,
                "stock":17.77,
                "percentITM":"-23.80",
                "last":0.14,
                "volume":100,
                "marginPrice":"0.18",
                "breakEvenPrice":"22.18",
                "breakEvenPercent":"24.85"
            },
            {
                "type":"Call",
                "code":"ANZ5X9",
                "expiry":"16/12/2021",
                "expiryInDays":470,
                "strike":12,
                "stock":17.77,
                "percentITM":"32.47",
                "last":5.85,
                "volume":60,
                "marginPrice":"6.45",
                "breakEvenPrice":"18.45",
                "breakEvenPercent":"3.83"
            },
            {
                "type":"Put",
                "code":"ANZXH8",
                "expiry":"15/06/2023",
                "expiryInDays":1016,
                "strike":18,
                "stock":17.77,
                "percentITM":"1.29",
                "last":3.89,
                "volume":8,
                "marginPrice":"3.87",
                "breakEvenPrice":"14.13",
                "breakEvenPercent":"-20.46"
            }
        ]
    },
    {
        "AWC":[
            {
                "type":"Put",
                "code":"AWCFQ9",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":1.96,
                "stock":1.53,
                "percentITM":"28.10",
                "last":0,
                "volume":250,
                "marginPrice":"0.47",
                "breakEvenPrice":"1.49",
                "breakEvenPercent":"-2.29"
            }
        ]
    },
    {
        "AZJ":[
            {
                "type":"Call",
                "code":"AZJZW9",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":4.5,
                "stock":4.28,
                "percentITM":"-5.14",
                "last":0.29,
                "volume":20,
                "marginPrice":"0.28",
                "breakEvenPrice":"4.78",
                "breakEvenPercent":"11.57"
            }
        ]
    },
    {
        "BHP":[
            {
                "type":"Call",
                "code":"BHP1K7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":38,
                "stock":37.5,
                "percentITM":"-1.33",
                "last":2.06,
                "volume":626,
                "marginPrice":"2.29",
                "breakEvenPrice":"40.28",
                "breakEvenPercent":"7.43"
            },
            {
                "type":"Call",
                "code":"BHPPZ9",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":38.01,
                "stock":37.5,
                "percentITM":"-1.36",
                "last":2.205,
                "volume":200,
                "marginPrice":"2.04",
                "breakEvenPrice":"40.05",
                "breakEvenPercent":"6.80"
            },
            {
                "type":"Call",
                "code":"BHPCY9",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":36.91,
                "stock":37.5,
                "percentITM":"1.57",
                "last":2.75,
                "volume":30,
                "marginPrice":"3.07",
                "breakEvenPrice":"39.98",
                "breakEvenPercent":"6.61"
            },
            {
                "type":"Call",
                "code":"BHPME8",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":37.86,
                "stock":37.5,
                "percentITM":"-0.96",
                "last":0,
                "volume":500,
                "marginPrice":"2.73",
                "breakEvenPrice":"40.59",
                "breakEvenPercent":"8.23"
            },
            {
                "type":"Put",
                "code":"BHPPQ9",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":33.51,
                "stock":37.5,
                "percentITM":"-10.64",
                "last":1.73,
                "volume":18,
                "marginPrice":"1.64",
                "breakEvenPrice":"31.87",
                "breakEvenPercent":"-15.00"
            },
            {
                "type":"Put",
                "code":"BHPVG9",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":30.68,
                "stock":37.5,
                "percentITM":"-18.19",
                "last":1.32,
                "volume":50,
                "marginPrice":"0.00",
                "breakEvenPrice":"30.68",
                "breakEvenPercent":"-18.19"
            }
        ]
    },
    {
        "BLD":[
            {
                "type":"Call",
                "code":"BLDLY7",
                "expiry":"16/09/2021",
                "expiryInDays":379,
                "strike":3,
                "stock":3.86,
                "percentITM":"22.28",
                "last":1.025,
                "volume":90,
                "marginPrice":"1.15",
                "breakEvenPrice":"4.15",
                "breakEvenPercent":"7.51"
            }
        ]
    },
    {
        "CBA":[
            {
                "type":"Call",
                "code":"CBAYW8",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":66.01,
                "stock":66.79,
                "percentITM":"1.17",
                "last":4.3,
                "volume":6,
                "marginPrice":"5.42",
                "breakEvenPrice":"71.44",
                "breakEvenPercent":"6.95"
            },
            {
                "type":"Call",
                "code":"CBA2H8",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":76,
                "stock":66.79,
                "percentITM":"-13.79",
                "last":1.9,
                "volume":7,
                "marginPrice":"2.18",
                "breakEvenPrice":"78.18",
                "breakEvenPercent":"17.05"
            },
            {
                "type":"Call",
                "code":"CBAMZ7",
                "expiry":"15/06/2023",
                "expiryInDays":1016,
                "strike":60,
                "stock":66.79,
                "percentITM":"10.17",
                "last":11.5,
                "volume":5,
                "marginPrice":"12.18",
                "breakEvenPrice":"72.17",
                "breakEvenPercent":"8.06"
            },
            {
                "type":"Put",
                "code":"CBAN97",
                "expiry":"15/06/2023",
                "expiryInDays":1016,
                "strike":68,
                "stock":66.79,
                "percentITM":"1.81",
                "last":13.19,
                "volume":4,
                "marginPrice":"12.57",
                "breakEvenPrice":"55.42",
                "breakEvenPercent":"-17.02"
            }
        ]
    },
    {
        "CSL":[
            {
                "type":"Call",
                "code":"CSLQW8",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":280,
                "stock":281.6,
                "percentITM":"0.57",
                "last":20,
                "volume":1,
                "marginPrice":"23.36",
                "breakEvenPrice":"303.37",
                "breakEvenPercent":"7.73"
            },
            {
                "type":"Call",
                "code":"CSLZT8",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":300,
                "stock":281.6,
                "percentITM":"-6.53",
                "last":15,
                "volume":1,
                "marginPrice":"17.56",
                "breakEvenPrice":"317.56",
                "breakEvenPercent":"12.77"
            },
            {
                "type":"Call",
                "code":"CSLRG8",
                "expiry":"16/09/2021",
                "expiryInDays":379,
                "strike":280,
                "stock":281.6,
                "percentITM":"0.57",
                "last":29,
                "volume":1,
                "marginPrice":"30.70",
                "breakEvenPrice":"310.70",
                "breakEvenPercent":"10.34"
            },
            {
                "type":"Call",
                "code":"CSLRI8",
                "expiry":"16/09/2021",
                "expiryInDays":379,
                "strike":284,
                "stock":281.6,
                "percentITM":"-0.85",
                "last":26.79,
                "volume":1,
                "marginPrice":"28.65",
                "breakEvenPrice":"312.65",
                "breakEvenPercent":"11.03"
            }
        ]
    },
    {
        "CWN":[
            {
                "type":"Call",
                "code":"CWNFQ8",
                "expiry":"16/09/2021",
                "expiryInDays":379,
                "strike":9.5,
                "stock":9.02,
                "percentITM":"-5.32",
                "last":0.8,
                "volume":40,
                "marginPrice":"0.83",
                "breakEvenPrice":"10.34",
                "breakEvenPercent":"14.58"
            }
        ]
    },
    {
        "FLT":[
            {
                "type":"Call",
                "code":"FLTWX7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":13.24,
                "stock":12.47,
                "percentITM":"-6.17",
                "last":1.615,
                "volume":15,
                "marginPrice":"1.98",
                "breakEvenPrice":"15.21",
                "breakEvenPercent":"22.01"
            },
            {
                "type":"Call",
                "code":"FLTG38",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":20.51,
                "stock":12.47,
                "percentITM":"-64.47",
                "last":0.24,
                "volume":35,
                "marginPrice":"0.26",
                "breakEvenPrice":"20.77",
                "breakEvenPercent":"66.52"
            },
            {
                "type":"Call",
                "code":"FLTNU8",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":8,
                "stock":12.47,
                "percentITM":"35.85",
                "last":4.95,
                "volume":140,
                "marginPrice":"5.61",
                "breakEvenPrice":"13.61",
                "breakEvenPercent":"9.14"
            },
            {
                "type":"Call",
                "code":"FLTML8",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":20,
                "stock":12.47,
                "percentITM":"-60.38",
                "last":0.4,
                "volume":200,
                "marginPrice":"0.48",
                "breakEvenPrice":"20.48",
                "breakEvenPercent":"64.23"
            }
        ]
    },
    {
        "FMG":[
            {
                "type":"Call",
                "code":"FMGJZ7",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":16.96,
                "stock":17.62,
                "percentITM":"3.75",
                "last":1.8,
                "volume":30,
                "marginPrice":"1.89",
                "breakEvenPrice":"18.85",
                "breakEvenPercent":"6.98"
            },
            {
                "type":"Put",
                "code":"FMG4Q9",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":14.67,
                "stock":17.62,
                "percentITM":"-16.74",
                "last":1.07,
                "volume":10,
                "marginPrice":"1.05",
                "breakEvenPrice":"13.62",
                "breakEvenPercent":"-22.70"
            }
        ]
    },
    {
        "GPT":[
            {
                "type":"Put",
                "code":"GPTPN9",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":4.81,
                "stock":3.71,
                "percentITM":"29.65",
                "last":0,
                "volume":50,
                "marginPrice":"1.11",
                "breakEvenPrice":"3.70",
                "breakEvenPercent":"-0.27"
            }
        ]
    },
    {
        "IAG":[
            {
                "type":"Call",
                "code":"IAGIT9",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":4.7,
                "stock":4.78,
                "percentITM":"1.67",
                "last":0.45,
                "volume":10,
                "marginPrice":"0.48",
                "breakEvenPrice":"5.18",
                "breakEvenPercent":"8.37"
            },
            {
                "type":"Put",
                "code":"IAGMW9",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":6.01,
                "stock":4.78,
                "percentITM":"25.73",
                "last":0,
                "volume":40,
                "marginPrice":"1.35",
                "breakEvenPrice":"4.65",
                "breakEvenPercent":"-2.62"
            }
        ]
    },
    {
        "MQG":[
            {
                "type":"Put",
                "code":"MQGS59",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":116.01,
                "stock":125.6,
                "percentITM":"-7.64",
                "last":5.85,
                "volume":10,
                "marginPrice":"4.96",
                "breakEvenPrice":"111.06",
                "breakEvenPercent":"-11.58"
            }
        ]
    },
    {
        "NAB":[
            {
                "type":"Call",
                "code":"NABL68",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":18,
                "stock":17.4,
                "percentITM":"-3.45",
                "last":0,
                "volume":100,
                "marginPrice":"1.17",
                "breakEvenPrice":"19.17",
                "breakEvenPercent":"10.17"
            },
            {
                "type":"Call",
                "code":"NABCI8",
                "expiry":"16/06/2022",
                "expiryInDays":652,
                "strike":24,
                "stock":17.4,
                "percentITM":"-37.93",
                "last":4.015,
                "volume":300,
                "marginPrice":"0.34",
                "breakEvenPrice":"24.34",
                "breakEvenPercent":"39.89"
            },
            {
                "type":"Call",
                "code":"NABWG7",
                "expiry":"15/06/2023",
                "expiryInDays":1016,
                "strike":20,
                "stock":17.4,
                "percentITM":"-14.94",
                "last":0,
                "volume":300,
                "marginPrice":"1.27",
                "breakEvenPrice":"21.27",
                "breakEvenPercent":"22.24"
            },
            {
                "type":"Put",
                "code":"NABWD7",
                "expiry":"15/06/2023",
                "expiryInDays":1016,
                "strike":18,
                "stock":17.4,
                "percentITM":"3.45",
                "last":3.89,
                "volume":8,
                "marginPrice":"3.98",
                "breakEvenPrice":"14.02",
                "breakEvenPercent":"-19.45"
            }
        ]
    },
    {
        "NCM":[
            {
                "type":"Call",
                "code":"NCMJV7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":32,
                "stock":31.87,
                "percentITM":"-0.41",
                "last":2.82,
                "volume":17,
                "marginPrice":"3.24",
                "breakEvenPrice":"35.24",
                "breakEvenPercent":"10.57"
            },
            {
                "type":"Call",
                "code":"NCMQM7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":32.5,
                "stock":31.87,
                "percentITM":"-1.98",
                "last":2.78,
                "volume":33,
                "marginPrice":"3.04",
                "breakEvenPrice":"35.53",
                "breakEvenPercent":"11.50"
            },
            {
                "type":"Call",
                "code":"NCMQT7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":34,
                "stock":31.87,
                "percentITM":"-6.68",
                "last":2.55,
                "volume":120,
                "marginPrice":"2.46",
                "breakEvenPrice":"36.47",
                "breakEvenPercent":"14.42"
            },
            {
                "type":"Call",
                "code":"NCMIM7",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":32.01,
                "stock":31.87,
                "percentITM":"-0.44",
                "last":0,
                "volume":5,
                "marginPrice":"3.90",
                "breakEvenPrice":"35.91",
                "breakEvenPercent":"12.66"
            },
            {
                "type":"Call",
                "code":"NCMU79",
                "expiry":"16/12/2021",
                "expiryInDays":470,
                "strike":30,
                "stock":31.87,
                "percentITM":"5.87",
                "last":0,
                "volume":30,
                "marginPrice":"5.83",
                "breakEvenPrice":"35.83",
                "breakEvenPercent":"12.43"
            }
        ]
    },
    {
        "QAN":[
            {
                "type":"Put",
                "code":"QANRZ7",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":3,
                "stock":3.89,
                "percentITM":"-22.88",
                "last":0.165,
                "volume":300,
                "marginPrice":"0.14",
                "breakEvenPrice":"2.87",
                "breakEvenPercent":"-26.35"
            }
        ]
    },
    {
        "QBE":[
            {
                "type":"Call",
                "code":"QBECR9",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":10.5,
                "stock":9.94,
                "percentITM":"-5.63",
                "last":0.67,
                "volume":50,
                "marginPrice":"0.95",
                "breakEvenPrice":"11.46",
                "breakEvenPercent":"15.24"
            },
            {
                "type":"Put",
                "code":"QBEBR8",
                "expiry":"15/06/2023",
                "expiryInDays":1016,
                "strike":10,
                "stock":9.94,
                "percentITM":"0.60",
                "last":2.19,
                "volume":15,
                "marginPrice":"1.95",
                "breakEvenPrice":"8.05",
                "breakEvenPercent":"-18.96"
            }
        ]
    },
    {
        "RIO":[
            {
                "type":"Call",
                "code":"RIOZD8",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":97.33,
                "stock":97.48,
                "percentITM":"0.15",
                "last":7.36,
                "volume":10,
                "marginPrice":"7.96",
                "breakEvenPrice":"105.28",
                "breakEvenPercent":"8.01"
            },
            {
                "type":"Put",
                "code":"RIOB17",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":91.61,
                "stock":97.48,
                "percentITM":"-6.02",
                "last":0,
                "volume":15,
                "marginPrice":"6.77",
                "breakEvenPrice":"84.84",
                "breakEvenPercent":"-12.97"
            }
        ]
    },
    {
        "STO":[
            {
                "type":"Call",
                "code":"STOY49",
                "expiry":"16/09/2021",
                "expiryInDays":379,
                "strike":5.5,
                "stock":5.46,
                "percentITM":"-0.73",
                "last":0.705,
                "volume":55,
                "marginPrice":"0.82",
                "breakEvenPrice":"6.32",
                "breakEvenPercent":"15.75"
            }
        ]
    },
    {
        "SYD":[
            {
                "type":"Call",
                "code":"SYDEZ7",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":5.84,
                "stock":5.65,
                "percentITM":"-3.36",
                "last":0.545,
                "volume":50,
                "marginPrice":"0.57",
                "breakEvenPrice":"6.41",
                "breakEvenPercent":"13.45"
            }
        ]
    },
    {
        "TLS":[
            {
                "type":"Call",
                "code":"TLSXD7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":2.93,
                "stock":2.83,
                "percentITM":"-3.53",
                "last":0,
                "volume":150,
                "marginPrice":"0.14",
                "breakEvenPrice":"3.08",
                "breakEvenPercent":"8.66"
            },
            {
                "type":"Call",
                "code":"TLSXG7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":3.02,
                "stock":2.83,
                "percentITM":"-6.71",
                "last":0,
                "volume":100,
                "marginPrice":"0.11",
                "breakEvenPrice":"3.13",
                "breakEvenPercent":"10.60"
            },
            {
                "type":"Call",
                "code":"TLSRL8",
                "expiry":"16/09/2021",
                "expiryInDays":379,
                "strike":2.94,
                "stock":2.83,
                "percentITM":"-3.89",
                "last":0.205,
                "volume":190,
                "marginPrice":"0.22",
                "breakEvenPrice":"3.16",
                "breakEvenPercent":"11.66"
            },
            {
                "type":"Call",
                "code":"TLSRI9",
                "expiry":"15/12/2022",
                "expiryInDays":834,
                "strike":2.94,
                "stock":2.83,
                "percentITM":"-3.89",
                "last":0.29,
                "volume":20,
                "marginPrice":"0.30",
                "breakEvenPrice":"3.24",
                "breakEvenPercent":"14.49"
            },
            {
                "type":"Put",
                "code":"TLSXJ7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":3.12,
                "stock":2.83,
                "percentITM":"10.25",
                "last":0,
                "volume":25,
                "marginPrice":"0.34",
                "breakEvenPrice":"2.78",
                "breakEvenPercent":"-1.77"
            },
            {
                "type":"Put",
                "code":"TLSNO8",
                "expiry":"15/06/2023",
                "expiryInDays":1016,
                "strike":2.97,
                "stock":2.83,
                "percentITM":"4.95",
                "last":0.565,
                "volume":45,
                "marginPrice":"0.54",
                "breakEvenPrice":"2.43",
                "breakEvenPercent":"-14.13"
            }
        ]
    },
    {
        "TWE":[
            {
                "type":"Call",
                "code":"TWEMR8",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":9.75,
                "stock":9.22,
                "percentITM":"-5.75",
                "last":0.775,
                "volume":56,
                "marginPrice":"0.78",
                "breakEvenPrice":"10.53",
                "breakEvenPercent":"14.21"
            }
        ]
    },
    {
        "WBC":[
            {
                "type":"Call",
                "code":"WBCPT7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":16.5,
                "stock":17.05,
                "percentITM":"3.23",
                "last":1.44,
                "volume":400,
                "marginPrice":"1.77",
                "breakEvenPrice":"18.27",
                "breakEvenPercent":"7.18"
            },
            {
                "type":"Call",
                "code":"WBCYH9",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":17,
                "stock":17.05,
                "percentITM":"0.29",
                "last":1.15,
                "volume":200,
                "marginPrice":"1.47",
                "breakEvenPrice":"18.47",
                "breakEvenPercent":"8.33"
            },
            {
                "type":"Call",
                "code":"WBCPV7",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":17.5,
                "stock":17.05,
                "percentITM":"-2.64",
                "last":0.97,
                "volume":100,
                "marginPrice":"1.21",
                "breakEvenPrice":"18.70",
                "breakEvenPercent":"9.71"
            },
            {
                "type":"Call",
                "code":"WBCYJ9",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":17,
                "stock":17.05,
                "percentITM":"0.29",
                "last":1.425,
                "volume":40,
                "marginPrice":"1.65",
                "breakEvenPrice":"18.64",
                "breakEvenPercent":"9.35"
            },
            {
                "type":"Put",
                "code":"WBCP67",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":23.01,
                "stock":17.05,
                "percentITM":"34.96",
                "last":8.055,
                "volume":20,
                "marginPrice":"5.87",
                "breakEvenPrice":"17.15",
                "breakEvenPercent":"0.56"
            }
        ]
    },
    {
        "WOR":[
            {
                "type":"Call",
                "code":"WORYV7",
                "expiry":"17/06/2021",
                "expiryInDays":288,
                "strike":9.5,
                "stock":9.4,
                "percentITM":"-1.06",
                "last":1.03,
                "volume":4,
                "marginPrice":"1.00",
                "breakEvenPrice":"10.50",
                "breakEvenPercent":"11.70"
            }
        ]
    },
    {
        "WOW":[
            {
                "type":"Call",
                "code":"WOWW58",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":30.01,
                "stock":38.21,
                "percentITM":"21.46",
                "last":0,
                "volume":250,
                "marginPrice":"9.39",
                "breakEvenPrice":"39.40",
                "breakEvenPercent":"3.11"
            },
            {
                "type":"Put",
                "code":"WOWWC8",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":36.01,
                "stock":38.21,
                "percentITM":"-5.76",
                "last":1.25,
                "volume":100,
                "marginPrice":"1.07",
                "breakEvenPrice":"34.93",
                "breakEvenPercent":"-8.57"
            }
        ]
    },
    {
        "WPL":[
            {
                "type":"Call",
                "code":"WPLIK9",
                "expiry":"18/03/2021",
                "expiryInDays":197,
                "strike":24,
                "stock":19.01,
                "percentITM":"-26.25",
                "last":0.12,
                "volume":50,
                "marginPrice":"0.14",
                "breakEvenPrice":"24.14",
                "breakEvenPercent":"27.01"
            },
            {
                "type":"Call",
                "code":"WPLST9",
                "expiry":"16/06/2022",
                "expiryInDays":652,
                "strike":20,
                "stock":19.01,
                "percentITM":"-5.21",
                "last":1.95,
                "volume":15,
                "marginPrice":"2.25",
                "breakEvenPrice":"22.25",
                "breakEvenPercent":"17.04"
            },
            {
                "type":"Call",
                "code":"WPLU58",
                "expiry":"15/12/2022",
                "expiryInDays":834,
                "strike":36,
                "stock":19.01,
                "percentITM":"-89.37",
                "last":0.125,
                "volume":25,
                "marginPrice":"0.23",
                "breakEvenPrice":"36.23",
                "breakEvenPercent":"90.61"
            }
        ]
    }
]